name: catalysee
favicon: null
layout_spectrum: 0.3684374715667218
typography_spectrum: 0.07021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4173408921342343
  lightness: 0.6195564835797995
  saturation: 0.648419309174642
  rhythmicContrast: 0.9483399116434157
purpose: []
