name: catalysee
favicon: null
layout_spectrum: 0.3684374715667218
typography_spectrum: 0.04816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#424242'
    - '#ffffff'
    - '#7b7b7b'
    - '#a2a2a2'
  brandStrength: 0.3125
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
